HW1 document
================

``` r
 library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
 library(moderndive)
```

## Problem 1

``` r
data ("early_january_weather")

 nrow(early_january_weather)
```

    ## [1] 358

``` r
 ncol(early_january_weather)
```

    ## [1] 15

``` r
mean (early_january_weather $ temp,)
```

    ## [1] 39.58212

\##The dataset shows 358 entries and 15 total columns, the mean
temperature is 39.58##

## plot

``` r
scatter_plot <- ggplot ( data=early_january_weather, aes(x=time_hour, y=temp, color=humid)) + geom_point()
print(scatter_plot)
```

![](p8105_hw1_rh3132_files/figure-gfm/templot-1.png)<!-- -->

``` r
##The scatter plot displays a collection of points that vary with both highs and lows, but overall there is a positive trend. ##

ggsave( "scatterplot_temp_vs_time_hour.png" , plot = scatter_plot,
       width = 10, height = 6, units = "in" )
```

## Problem 2

``` r
my_tibble <- tibble(
      numeric_vector = rnorm ( 10 ),
      logical_vector = numeric_vector > 0,
      character_vector = c("Monday", "Tuesday", "Wednesday", "apple", "cherry", "low", "medium", "high", "happy", "sad"),
      factor_vector = factor (c("Monday", "Tuesday", "Wednesday", "apple", "cherry", "low", "medium", "high", "happy", "sad"))
)
```

``` r
my_tibble
```

    ## # A tibble: 10 × 4
    ##    numeric_vector logical_vector character_vector factor_vector
    ##             <dbl> <lgl>          <chr>            <fct>        
    ##  1         -0.133 FALSE          Monday           Monday       
    ##  2          0.382 TRUE           Tuesday          Tuesday      
    ##  3          1.10  TRUE           Wednesday        Wednesday    
    ##  4         -0.315 FALSE          apple            apple        
    ##  5          0.165 TRUE           cherry           cherry       
    ##  6         -0.231 FALSE          low              low          
    ##  7          1.49  TRUE           medium           medium       
    ##  8          0.910 TRUE           high             high         
    ##  9          1.12  TRUE           happy            happy        
    ## 10          0.318 TRUE           sad              sad

``` r
mean (my_tibble $ numeric_vector)
```

    ## [1] 0.4795122

``` r
mean (my_tibble $ logical_vector)
```

    ## [1] 0.7

``` r
mean (my_tibble $ character_vector)
```

    ## Warning in mean.default(my_tibble$character_vector): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean (my_tibble $ factor_vector)
```

    ## Warning in mean.default(my_tibble$factor_vector): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

\####For the variables, only numeric and logical works in taking the
mean.####

``` r
numeric_from_logical <- as.numeric( my_tibble $ logical_vector )

numeric_from_char <- as.numeric( my_tibble $ character_vector )
```

    ## Warning: NAs introduced by coercion

``` r
numeric_from_factor <- as.numeric( my_tibble $ factor_vector )
```

\###Logical to numeric will work without issues, converting TRUE to 1
and FALSE to 0. Character to numeric result in NAs, as strings can’t be
naturally converted to numbers. Factor to numeric will convert the
factor levels to their underlying integer representation.###

## FINISHED
